spring:
  application:
    name: GestionUsuarios
  datasource:
    url: jdbc:postgresql://localhost:5432/GestionUsuarios
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

email:
  username: ${EMAIL_USERNAME}    
  password: ${EMAIL_PASSWORD} 
  host: smtp.gmail.com
  port: 587
  protocol: smtp
  tls: true
  auth: true
  debug: false

frontend:
  frontendUrl: ${FRONTEND_BASE_URL}

app:
  verification:
    code:
      expiration: 15   
