spring:
  application:
    name: GestionUsuarios
  datasource:
    url: jdbc:postgresql://localhost:5432/GestionUsuarios
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true